# git-pull
# Autogenerated from man page /usr/local/share/man/man1/git-pull.1
# using Deroffing man parser
complete -c git-pull -s e --description 'Invoke an editor before committing successful m… [See Man Page]'
complete -c git-pull -l 'rebase[' --description 'When true, rebase the current branch on top of … [See Man Page]'
complete -c git-pull -o 'e)' --description '.'
complete -c git-pull -l preserve-merges --description 'along to git rebase so that locally created mer… [See Man Page]'

