# git-config
# Autogenerated from man page /usr/local/share/man/man1/git-config.1
# using Deroffing man parser
complete -c git-config -l get-urlmatch --description 'When given a two-part name section. key, the value for section.'
complete -c git-config -l local --description 'For writing options: write to the repository . git/config file.'
complete -c git-config -l blob --description 'Similar to --file but use the given blob instead of a file.  E.'
complete -c git-config -l prune --description 'option was given on the command line.  See also remote. <name>.'
complete -c git-config -l quiet --description 'was used for the fetch, pack-objects will outpu… [See Man Page]'

