# git-rev-list
# Autogenerated from man page /usr/local/share/man/man1/git-rev-list.1
# using Deroffing man parser
complete -c git-rev-list -l author-date-order --description 'Show no parents before all of its children are … [See Man Page]'
complete -c git-rev-list -l encoding --description 'The commit objects record the encoding used for… [See Man Page]'
complete -c git-rev-list -l 'no-walk.' --description '.'
complete -c git-rev-list -l 'pretty.' --description 'log.'

