# git
# Autogenerated from man page /usr/local/share/man/man1/git.1
# using Deroffing man parser
complete -c git -s C --description 'Run as if git was started in <path> instead of … [See Man Page]'
complete -c git -l glob-pathspecs --description 'Add "glob" magic to all pathspec.'
complete -c git -l noglob-pathspecs --description 'Add "literal" magic to all pathspec.'
complete -c git -l icase-pathspecs --description 'Add "icase" magic to all pathspec.'

