# git-merge-file
# Autogenerated from man page /usr/local/share/man/man1/git-merge-file.1
# using Deroffing man parser
complete -c git-merge-file -l diff3 --description 'Show conflicts in "diff3" style.'

