# git-send-email
# Autogenerated from man page /usr/local/share/man/man1/git-send-email.1
# using Deroffing man parser
complete -c git-send-email -l smtp-ssl-cert-path --description 'Path to ca-certificates (either a directory or a single file).'

