# git-gc
# Autogenerated from man page /usr/local/share/man/man1/git-gc.1
# using Deroffing man parser
complete -c git-gc -l force --description 'Force git gc to run even if there may be anothe… [See Man Page]'

