# git-merge
# Autogenerated from man page /usr/local/share/man/man1/git-merge.1
# using Deroffing man parser
complete -c git-merge -s e --description 'Invoke an editor before committing successful m… [See Man Page]'
complete -c git-merge -o 'S[<keyid>]' -l 'gpg-sign[' --description 'GPG-sign the resulting merge commit.'
complete -c git-merge -o 'e)' --description '.'

