# git-push
# Autogenerated from man page /usr/local/share/man/man1/git-push.1
# using Deroffing man parser
complete -c git-push -l '[no-]force-with-lease' -l force-with-lease -l force-with-lease --description 'Usually, "git push" refuses to update a remote … [See Man Page]'
complete -c git-push -l '[no-]verify' --description 'Toggle the pre-push hook (see githooks(5)).'

