# DVTiPhoneSimulatorBridgeService
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/usr/share/man/man1/DVTiPhoneSimulatorBridgeService.1
# using Darwin man parser
complete -c DVTiPhoneSimulatorBridgeService -s a --description 'Description of -a flag.'
complete -c DVTiPhoneSimulatorBridgeService -s b --description 'Description of -b flag \\" Ends the list Pp .'

