# git-rev-parse
# Autogenerated from man page /usr/local/share/man/man1/git-rev-parse.1
# using Deroffing man parser
complete -c git-rev-parse -l prefix --description 'Behave as if git rev-parse was invoked from the… [See Man Page]'

