# git-fetch-pack
# Autogenerated from man page /usr/local/share/man/man1/git-fetch-pack.1
# using Deroffing man parser
complete -c git-fetch-pack -l check-self-contained-and-connected --description 'Output "connectivity-ok" if the received pack i… [See Man Page]'

