# git-cherry
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/usr/share/man/man1/git-cherry.1
# using Deroffing man parser
complete -c git-cherry -s v --description 'Verbose.'

