# git-credential-store
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/usr/share/man/man1/git-credential-store.1
# using Deroffing man parser
complete -c git-credential-store -l store --description 'Use <path> to store credentials.'

