# git-clean
# Autogenerated from man page /usr/local/share/man/man1/git-clean.1
# using Deroffing man parser
complete -c git-clean -s i -l interactive --description 'Show what would be done and clean files interactively.'

