# git-diff-files
# Autogenerated from man page /usr/local/share/man/man1/git-diff-files.1
# using Deroffing man parser
complete -c git-diff-files -s s -l no-patch --description 'Suppress diff output.'
complete -c git-diff-files -l ignore-blank-lines --description 'Ignore changes whose lines are all blank.'
complete -c git-diff-files -l 'patch.' --description '.'
complete -c git-diff-files -o 'S<regex>' --description 'and.'

