# git-submodule
# Autogenerated from man page /usr/local/share/man/man1/git-submodule.1
# using Deroffing man parser
complete -c git-submodule -l depth --description 'This option is valid for add and update commands.'

