# git-describe
# Autogenerated from man page /usr/local/share/man/man1/git-describe.1
# using Deroffing man parser
complete -c git-describe -l first-parent --description 'Follow only the first parent commit upon seeing a merge commit.'

