# git-bisect
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/usr/share/man/man1/git-bisect.1
# using Deroffing man parser
complete -c git-bisect -l no-checkout --description 'Do not checkout the new working tree at each it… [See Man Page]'

