# git-diff-index
# Autogenerated from man page /usr/local/share/man/man1/git-diff-index.1
# using Deroffing man parser
complete -c git-diff-index -s s -l no-patch --description 'Suppress diff output.'
complete -c git-diff-index -l ignore-blank-lines --description 'Ignore changes whose lines are all blank.'
complete -c git-diff-index -l 'patch.' --description '.'
complete -c git-diff-index -o 'S<regex>' --description 'and.'

