# git-format-patch
# Autogenerated from man page /usr/local/share/man/man1/git-format-patch.1
# using Deroffing man parser
complete -c git-format-patch -l no-patch --description 'Suppress diff output.'
complete -c git-format-patch -l ignore-blank-lines --description 'Ignore changes whose lines are all blank.'
complete -c git-format-patch -l from -l from --description 'Use ident in the From: header of each commit email.'
complete -c git-format-patch -s q --description 'Do not print the names of the generated files t… [See Man Page]'
complete -c git-format-patch -l 'patch.' --description '.'

