# git-check-ignore
# Autogenerated from man page /usr/local/share/man/man1/git-check-ignore.1
# using Deroffing man parser
complete -c git-check-ignore -s n -l non-matching --description 'Show given paths which don\\(cqt match any pattern.'
complete -c git-check-ignore -l no-index --description 'Don\\(cqt look in the index when undertaking the checks.'

