# git-diff-tree
# Autogenerated from man page /usr/local/share/man/man1/git-diff-tree.1
# using Deroffing man parser
complete -c git-diff-tree -l no-patch --description 'Suppress diff output.'
complete -c git-diff-tree -l ignore-blank-lines --description 'Ignore changes whose lines are all blank.'
complete -c git-diff-tree -l encoding --description 'The commit objects record the encoding used for… [See Man Page]'
complete -c git-diff-tree -l 'patch.' --description '.'
complete -c git-diff-tree -o 'S<regex>' --description 'and.'

