# git-grep
# Autogenerated from man page /usr/local/share/man/man1/git-grep.1
# using Deroffing man parser
complete -c git-grep -l textconv --description 'Honor textconv filter settings.'
complete -c git-grep -l no-textconv --description 'Do not honor textconv filter settings.  This is the default.'

