# git-index-pack
# Autogenerated from man page /usr/local/share/man/man1/git-index-pack.1
# using Deroffing man parser
complete -c git-index-pack -l check-self-contained-and-connected --description 'Die if the pack contains broken links.  For internal use only.'

