# xctest
# Autogenerated from man page /Applications/Xcode.app/Contents/Developer/usr/share/man/man1/xctest.1
# using Darwin man parser
complete -c xctest -o test --description 'This flag denotes the scope of the unit test to be run.'

