# git-log
# Autogenerated from man page /usr/local/share/man/man1/git-log.1
# using Deroffing man parser
complete -c git-log -s L -s L --description 'Trace the evolution of the line range given by … [See Man Page]'
complete -c git-log -l author-date-order --description 'Show no parents before all of its children are … [See Man Page]'
complete -c git-log -l encoding --description 'The commit objects record the encoding used for… [See Man Page]'
complete -c git-log -l 'no-walk.' --description '.'
complete -c git-log -l 'pretty.' --description 'log.'
complete -c git-log -l no-patch --description '.'
complete -c git-log -l 'patch.' --description '.'
complete -c git-log -o 'S<regex>' --description 'and.'
complete -c git-log -l ignore-blank-lines --description '.'

