# git-diff
# Autogenerated from man page /usr/local/share/man/man1/git-diff.1
# using Deroffing man parser
complete -c git-diff -s s -l no-patch --description 'Suppress diff output.'
complete -c git-diff -l ignore-blank-lines --description 'Ignore changes whose lines are all blank.'
complete -c git-diff -l no-index --description 'option when running the command in a working tr… [See Man Page]'
complete -c git-diff -l 'patch.' --description '.'
complete -c git-diff -o 'S<regex>' --description 'and.'

