# git-remote
# Autogenerated from man page /usr/local/share/man/man1/git-remote.1
# using Deroffing man parser
complete -c git-remote -l auto --description 'HEAD, then the symbolic-ref refs/remotes/<name>… [See Man Page]'

