#!bin/bash

envup() {
  if [ -f .env ]; then
    source .env
    while read var; do
      if [[ $var != PATH* ]]; then
        export $var
      fi
    done < .env
    return 0
  else
    echo 'No .env file found' 1>&2
    return 1
  fi
}